baseURL = 'https://www.aidley.com/'
languageCode = 'en-us'
title = 'Tim Aidley'
theme = 'anatole'


[menu]

    [[menu.main]]
    name = "Home"
    identifer = "home"
    weight = 100
    url = "/"
    
    [[menu.main]]
    name = "Posts"
    weight = 200
    identifier = "posts"
    url = "/posts/"
    
    [[menu.main]]
    name = "About"
    weight = 300
    identifier = "about"
    url = "/about/"

[taxonomies]
    category = "categories"
    series = "series"
    tags = "tags"

[params]
title = "Tim Aidley"
author = "Tim Aidley"
profilePicture = "general/tim.jpg"
contentratio = 0.65
disableTitleCapitalization = false
readMore = true
relatedPosts = true
numberOfRelatedPosts = 3
copyright = "{{ YEAR }} Tim Aidley. üè≥Ô∏è‚Äç‚ößÔ∏è Trans rights are human rights."

[related]
  includeNewer = true
  threshold = 80
  toLower = true
    [[related.indices]]
      name = 'series'
      weight = 80
    [[related.indices]]
      name = 'keywords'
      weight = 100
    [[related.indices]]
      name = 'tags'
      weight = 80


    [[params.socialIcons]]
    icon = "fab fa-bluesky"
    title = "Bluesky"
    url = "https://bsky.app/profile/tim.aidley.com"
    
    [[params.socialIcons]]
    icon = "fab fa-mastodon"
    title = "Mastodon"
    url = "https://mastodon.gamedev.place/@planettimmy"
    
    [[params.socialIcons]]
    icon = "fab fa-github"
    title = "GitHub"
    url = "https://github.com/TimAidley"
    
    [[params.socialIcons]]
    icon = "fas fa-envelope"
    title = "email"
    url = "mailto:tim@aidley.com"
    
    [[params.socialIcons]]
    icon = "fab fa-linkedin"
    title = "LinkedIn"
    url = "https://www.linkedin.com/in/timaidley/"
